import type { Venue } from '@intent/types'

export const venues: Venue[] = [
  {
    id: 'cow-swap',
    family: 'evm' as const,
    name: 'CoW Swap',
    category: 'aggregator',
    chains: ['Ethereum', 'Arbitrum', 'Base', 'Gnosis'],
    bestFor: 'Large trades, MEV-safe',
    url: 'https://swap.cow.fi',
  },
  {
    id: '1inch',
    family: 'evm' as const,
    name: '1inch',
    category: 'aggregator',
    chains: ['Ethereum', 'Arbitrum', 'Optimism', 'Polygon', 'Base'],
    bestFor: 'All-round multichain default',
    url: 'https://1inch.io',
  },
  {
    id: 'uniswap',
    family: 'evm' as const,
    name: 'Uniswap',
    category: 'swap',
    chains: ['Ethereum', 'Arbitrum', 'Optimism', 'Base', 'Polygon'],
    bestFor: 'Deep AMM liquidity',
    url: 'https://uniswap.org',
  },
  {
    id: 'curve',
    family: 'evm' as const,
    name: 'Curve',
    category: 'swap',
    chains: ['Ethereum', 'Arbitrum', 'Optimism', 'Polygon'],
    bestFor: 'Stablecoin pairs',
    url: 'https://curve.fi',
  },
  {
    id: '0x',
    family: 'evm' as const,
    name: '0x',
    category: 'aggregator',
    chains: ['Ethereum', 'Arbitrum', 'Base', 'Polygon'],
    bestFor: 'RFQ + swap API',
    url: 'https://0x.org',
  },
  {
    id: 'kyberswap',
    family: 'evm' as const,
    name: 'KyberSwap',
    category: 'aggregator',
    chains: ['Ethereum', 'Arbitrum', 'Optimism', 'Polygon', 'Base'],
    bestFor: 'Dynamic routing',
    url: 'https://kyberswap.com',
  },
  {
    id: 'matcha',
    family: 'evm' as const,
    name: 'Matcha',
    category: 'aggregator',
    chains: ['Ethereum', 'Arbitrum', 'Base', 'Polygon'],
    bestFor: 'Best-price discovery',
    url: 'https://matcha.xyz',
  },
  {
    id: 'dydx',
    family: 'evm' as const,
    name: 'dYdX',
    category: 'orderbook',
    chains: ['dYdX Chain'],
    bestFor: 'Order book, perps',
    url: 'https://dydx.exchange',
  },
  {
    id: 'injective',
    family: 'evm' as const,
    name: 'Injective',
    category: 'orderbook',
    chains: ['Injective'],
    bestFor: 'On-chain order book',
    url: 'https://injective.com',
  },
  // Stellar-native venues. These trade Stellar assets through Soroban/SDEX and
  // have no EVM deployment, which is exactly why the Apps screen filters by
  // chain family rather than listing everything everywhere.
  {
    id: 'soroswap',
    name: 'Soroswap',
    family: 'stellar' as const,
    category: 'swap',
    chains: ['Stellar'],
    bestFor: 'Soroban AMM swaps',
    url: 'https://soroswap.finance',
    integration: 'executes',
    capability:
      'Intents route here through the Soroban router. On identical assets it has quoted several times the classic DEX price.',
  },
  {
    id: 'aquarius',
    name: 'Aquarius',
    family: 'stellar' as const,
    category: 'swap',
    chains: ['Stellar'],
    bestFor: 'Incentivised AMM pools',
    url: 'https://aqua.network',
    integration: 'listed',
  },
  {
    id: 'stellarx',
    name: 'StellarX',
    family: 'stellar' as const,
    category: 'orderbook',
    chains: ['Stellar'],
    bestFor: 'Native SDEX orderbook',
    url: 'https://www.stellarx.com',
    integration: 'executes',
    capability:
      'Swaps and resting limit orders settle on the network’s own order book, read and written directly rather than through a venue.',
  },
  {
    id: 'etherfuse',
    name: 'Etherfuse',
    family: 'stellar' as const,
    category: 'rwa',
    chains: ['Stellar'],
    bestFor: 'Tokenized sovereign debt',
    url: 'https://etherfuse.com',
    integration: 'executes',
    capability:
      'Buy tokenized Mexican, US and Korean treasury bills. They settle through the same path payments as any other classic asset, so no separate execution path was needed.',
  },
  {
    id: 'stellar-pools',
    name: 'Stellar Liquidity Pools',
    family: 'stellar' as const,
    category: 'pool',
    chains: ['Stellar'],
    bestFor: 'Fee income with no protocol risk',
    url: 'https://developers.stellar.org/docs/build/guides/liquidity-pools',
    integration: 'executes',
    capability:
      'Deposit both sides of a pair and earn a share of the 0.3% fee on trades routed through it. The network runs these, so there is no contract to trust and nothing that can be shut down.',
  },
  {
    id: 'blend',
    name: 'Blend Capital',
    family: 'stellar' as const,
    category: 'lending',
    chains: ['Stellar'],
    bestFor: 'Supply and borrow against collateral',
    url: 'https://blend.capital',
    integration: 'executes',
    capability:
      'Reserves and rates are read live, and XLM can be supplied. Borrowing stays out of scope on purpose: a supply-only position cannot be liquidated, and that guarantee holds only while nothing here can open a liability.',
  },
  {
    id: 'testanchor',
    name: 'SDF test anchor',
    family: 'stellar' as const,
    category: 'offramp',
    chains: ['Stellar'],
    bestFor: 'Withdrawing USDC to a (fake) bank on testnet',
    url: 'https://testanchor.stellar.org',
    integration: 'executes',
    capability:
      'SEP-24 withdrawal of USDC. The anchor hosts verification and bank details on its own page; this app sends the payment it names, with the memo it names, and nothing else.',
  },
  {
    id: 'moneygram',
    name: 'MoneyGram Access',
    family: 'stellar' as const,
    category: 'offramp',
    chains: ['Stellar'],
    bestFor: 'Cash pickup at MoneyGram locations',
    url: 'https://stellar.moneygram.com',
    integration: 'executes',
    capability:
      'SEP-24 withdrawal of USDC on the testnet deployment. Production access needs a commercial agreement with MoneyGram; the flow is identical.',
  },
  // Perpetual futures. `quotes`, not `executes`: the reads are live and the
  // order path is built, but the gateway mints the API key an order needs
  // only for wallets on its closed-beta allowlist (`beta-status` answered
  // `allowed: false` for every address tried on 2026-09-23), so no position
  // has been signed through this app end to end.
  {
    id: 'noether',
    name: 'Noether',
    family: 'stellar' as const,
    category: 'perps',
    chains: ['Stellar'],
    bestFor: 'Leveraged longs and shorts, up to 10x',
    // The site answers; its `api.` and `docs.` subdomains do not resolve.
    url: 'https://noether.exchange',
    integration: 'quotes',
    capability:
      'Mark prices, open interest and vault APY are read live for the agents, and "long XLM 10x with 50 USDC" prepares an isolated position through the gateway for review and signature. Signing needs an API key the gateway issues only inside its closed beta, so the sign path is unverified end to end. The protocol is unaudited and testnet-only; its gateway reports version 0.0.0-dev.',
  },
]
